name: Test
on: pull_request
permissions:
  checks: write
  pull-requests: write
jobs:
  run_tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Run unit tests
        run: ./gradlew clean koverXmlReport
        continue-on-error: true

      - name: Publish Test Results
        uses: EnricoMi/publish-unit-test-result-action@v2
        if: always()
        with:
          json_suite_details: true
          files: |
            **/inflekt-core/build/test-results/testDebugUnitTest/TEST*.xml

      - name: Publish Kover Reports
        id: kover
        uses: mi-kas/kover-report@v1
        with:
          path: |
            ${{ github.workspace }}/inflekt-core/build/reports/kover/report.xml
          title: Code Coverage
          update-comment: true
